[package]
name = "snarkos-node-bft-events-fuzz"
version = "2.1.7"
publish = false
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Event fuzzing for the gateway in a decentralized operating system"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/snarkOS"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [ "cryptography", "operating-systems" ]
license = "Apache-2.0"
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies.bytes]
version = "1"

[dependencies.libfuzzer-sys]
version = "0.4"

[dependencies.once_cell]
version = "1"

[dependencies.rand]
version = "0.8"

[dependencies.snarkos-node-bft-events]
path = ".."

[dependencies.snarkvm]
version = "=0.16.18"
features = [ "circuit", "console", "rocks" ]

[dependencies.snow]
version = "0.9"

[dependencies.tokio-util]
version = "0.7"
features = [ "codec" ]

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[profile.release]
debug = 1

[[bin]]
name = "codec"
path = "fuzz_targets/codec.rs"
test = false
doc = false
